# Generated by Django 3.1 on 2020-08-23 21:23

from django.db import migrations, models
import uuid


def fill_model_uuid(apps, schema_editor):
    MyModel = apps.get_model("agile", "Agile")
    for obj in MyModel.objects.all():
        obj.uuid = uuid.uuid4()
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("agile", "0002_alter_agile_principle_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="agile", name="uuid", field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.RunPython(code=fill_model_uuid),
    ]
