# Generated by Django 3.1 on 2020-08-23 21:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("agile", "0003_add_uuid_field"),
    ]

    operations = [
        migrations.RemoveField(model_name="agile", name="id",),
        migrations.AlterField(
            model_name="agile",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
