# Generated by Django 3.1 on 2020-08-23 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agile", "0004_replace_id_with_uuid"),
    ]

    operations = [
        migrations.RenameField(model_name="agile", old_name="uuid", new_name="id",),
    ]
